name: Build job

on:
  # Manual triggers
  workflow_dispatch:

jobs:
  build:
    name: Build app
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Clone Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'mihonapp/mihon'
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

      - name: Build APK
        run: ./gradlew assembleRelease -Pwith-analytics -Pwith-updater

      - name: Build APK (FOSS)
        run: |
          ./gradlew assembleFoss -Pwith-updater
          mv app/build/outputs/apk/foss/app-universal-foss-unsigned.apk app/build/outputs/apk/release

      - name: Sign APK
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@7a9ff16c8c6b7ead5d71c0f1cc61f2703170eade # v1.1.0
        with:
          myToken: ${{ github.token }}
          exclude_types: 'draft|prerelease'
          view_top: 1

      - name: Clean up build artifacts
        run: |
          set -e

          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-universal-release-unsigned-signed.apk mihon-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum mihon-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-universal-foss-unsigned-signed.apk mihon-r${{ env.COMMIT_COUNT }}-foss.apk
          sha=`sha256sum mihon-r${{ env.COMMIT_COUNT }}-foss.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_FOSS_SHA=$sha" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk mihon-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum mihon-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk mihon-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum mihon-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-x86-release-unsigned-signed.apk mihon-x86-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum mihon-x86-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-x86_64-release-unsigned-signed.apk mihon-x86_64-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum mihon-x86_64-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          name: Mihon Preview r${{ env.COMMIT_COUNT }}
          body: |
            ### Commits

            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | Universal (FOSS) | ${{ env.APK_UNIVERSAL_FOSS_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86 | ${{ env.APK_X86_SHA }} |
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
            
            ## If you are unsure which apk to download then go with mihon-r${{ env.COMMIT_COUNT }}.apk
          files: |
            mihon-r${{ env.COMMIT_COUNT }}.apk
            mihon-r${{ env.COMMIT_COUNT }}-foss.apk
            mihon-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk
            mihon-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk
            mihon-x86-r${{ env.COMMIT_COUNT }}.apk
            mihon-x86_64-r${{ env.COMMIT_COUNT }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@dfbe6be2a006e9475dfcbe5b8d201f1824c2a9fe # v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 28
          delete_tags: true
